#pragma once

enum class EntityType
{
    ENTITY_PLAYER,
    ENTITY_CURSOR,
    ENTITY_CELL_CONNECTOR,
    ENTITY_KEY,
    ENTITY_DOOR,
    ENTITY_FLOOR_GRASS,
    ENTITY_WALL,
    ENTITY_LEVEL,
    ENTITY_GRID,
    ENTITY_CELL
};
